In [1]:
import pandas as pd

In [5]:
import json

with open("steam_all_2005.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print(type(data))

<class 'dict'>

In [6]:
if isinstance(data, dict):
    print("Number of keys:", len(data))
    first_key = list(data.keys())[0]
    print("First key:", first_key)
    print(data[first_key])

elif isinstance(data, list):
    print("Number of items:", len(data))
    print(data[0])

Number of keys: 5
First key: ratings
['Overwhelmingly Positive', 'Very Positive', 'Mostly Positive', 'Positive', 'Mixed', 'Mostly Negative', 'Negative', 'Very Negative', 'Overwhelmingly Negative']

In [7]:
print(data.keys())

dict_keys(['ratings', 'genres', 'tags', 'games', 'meta'])

In [8]:
for key in data.keys():
    print(f"\n{key}")
    print(type(data[key]))

    if hasattr(data[key], "__len__"):
        print("Length:", len(data[key]))

ratings
<class 'list'>
Length: 9

genres
<class 'list'>
Length: 33

tags
<class 'list'>
Length: 50

games
<class 'list'>
Length: 82928

meta
<class 'dict'>
Length: 4

In [9]:
print(data["games"][0])

['Counter-Strike 2', 2012, 87, 8815087, 0.0, 1, [1, 8], [28, 18, 22, 2], 'Valve']

In [10]:
import pandas as pd

df = pd.DataFrame(data["games"])

df.head()

,0,1,2,3,4,5,6,7,8
0,Counter-Strike 2,2012,87,8815087,0.00,1,"[1, 8]","[28, 18, 22, 2]",Valve
1,PUBG: BATTLEGROUNDS,2017,59,2557944,0.00,4,"[1, 3, 11, 8]","[46, 18, 22, 28]",PUBG Corporation
2,Dota 2,2013,82,2498969,0.00,1,"[1, 5, 8]","[24, 22, 4]",Valve
3,Grand Theft Auto V Legacy,2015,87,1990556,0.00,1,"[1, 3]","[2, 22]",Rockstar North
4,Terraria,2011,97,1409473,4.99,0,"[1, 3, 0, 6]","[45, 46, 8, 22]",Re-Logic

In [11]:
df.columns.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82928 entries, 0 to 82927
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       82928 non-null  str
 1   1       82928 non-null  int64
 2   2       82928 non-null  int64
 3   3       82928 non-null  int64
 4   4       82928 non-null  float64
 5   5       82928 non-null  int64
 6   6       82928 non-null  object
 7   7       82928 non-null  object
 8   8       82928 non-null  str
dtypes: float64(1), int64(4), object(2), str(2)
memory usage: 8.3+ MB

In [15]:
from pprint import pprint

pprint(data["meta"])

{'count': 82928,
 'genre_matched': 82813,
 'source': 'fronkongames/steam-games-dataset (Jan 2026)',
 'yearRange': [2005, 2025]}

In [16]:
print(data["genres"])

['Indie', 'Action', 'Casual', 'Adventure', 'Simulation', 'Strategy', 'RPG', 'Early Access', 'Free To Play', 'Sports', 'Racing', 'Massively Multiplayer', 'Utilities', 'Design & Illustration', 'Violent', 'Animation & Modeling', 'Education', 'Video Production', 'Gore', 'Game Development', 'Audio Production', 'Software Training', 'Photo Editing', 'Nudity', 'Web Publishing', 'Sexual Content', 'Accounting', 'Movie', 'Documentary', 'Episodic', 'Short', 'Tutorial', '360 Video']

In [17]:
print(data["tags"][:10])

['Indie', 'Casual', 'Action', 'Adventure', 'Strategy', 'Simulation', 'Puzzle', 'RPG', '2D', 'Singleplayer']

In [18]:
for i in range(5):
    print(data["games"][i])

['Counter-Strike 2', 2012, 87, 8815087, 0.0, 1, [1, 8], [28, 18, 22, 2], 'Valve']
['PUBG: BATTLEGROUNDS', 2017, 59, 2557944, 0.0, 4, [1, 3, 11, 8], [46, 18, 22, 28], 'PUBG Corporation']
['Dota 2', 2013, 82, 2498969, 0.0, 1, [1, 5, 8], [24, 22, 4], 'Valve']
['Grand Theft Auto V Legacy', 2015, 87, 1990556, 0.0, 1, [1, 3], [2, 22], 'Rockstar North']
['Terraria', 2011, 97, 1409473, 4.99, 0, [1, 3, 0, 6], [45, 46, 8, 22], 'Re-Logic']

In [21]:
df.columns = [
    "name",          # Game name
    "release_year",  # Release year
    "review_score",  # Review score (0-100)
    "review_count",  # Number of reviews
    "price",         # Price in USD
    "rating_id",     # Encoded review category (to be verified)
    "genre_ids",     # List of genre indices
    "tag_ids",       # List of tag indices
    "developer"      # Developer
]

In [22]:
df.head()

,name,release_year,review_score,review_count,price,rating_id,genre_ids,tag_ids,developer
0,Counter-Strike 2,2012,87,8815087,0.00,1,"[1, 8]","[28, 18, 22, 2]",Valve
1,PUBG: BATTLEGROUNDS,2017,59,2557944,0.00,4,"[1, 3, 11, 8]","[46, 18, 22, 28]",PUBG Corporation
2,Dota 2,2013,82,2498969,0.00,1,"[1, 5, 8]","[24, 22, 4]",Valve
3,Grand Theft Auto V Legacy,2015,87,1990556,0.00,1,"[1, 3]","[2, 22]",Rockstar North
4,Terraria,2011,97,1409473,4.99,0,"[1, 3, 0, 6]","[45, 46, 8, 22]",Re-Logic

In [23]:
genres = data["genres"]

df["genres"] = df["genre_ids"].apply(
    lambda ids: [genres[i] for i in ids]
)

In [25]:
df[["genre_ids", "genres"]].head()

       genre_ids                                             genres
0         [1, 8]                             [Action, Free To Play]
1  [1, 3, 11, 8]  [Action, Adventure, Massively Multiplayer, Fre...
2      [1, 5, 8]                   [Action, Strategy, Free To Play]
3         [1, 3]                                [Action, Adventure]
4   [1, 3, 0, 6]                    [Action, Adventure, Indie, RPG]

In [26]:
df.head()

,name,release_year,review_score,review_count,price,rating_id,genre_ids,tag_ids,developer,genres
0,Counter-Strike 2,2012,87,8815087,0.00,1,"[1, 8]","[28, 18, 22, 2]",Valve,"[Action, Free To Play]"
1,PUBG: BATTLEGROUNDS,2017,59,2557944,0.00,4,"[1, 3, 11, 8]","[46, 18, 22, 28]",PUBG Corporation,"[Action, Adventure, Massively Multiplayer, Fre..."
2,Dota 2,2013,82,2498969,0.00,1,"[1, 5, 8]","[24, 22, 4]",Valve,"[Action, Strategy, Free To Play]"
3,Grand Theft Auto V Legacy,2015,87,1990556,0.00,1,"[1, 3]","[2, 22]",Rockstar North,"[Action, Adventure]"
4,Terraria,2011,97,1409473,4.99,0,"[1, 3, 0, 6]","[45, 46, 8, 22]",Re-Logic,"[Action, Adventure, Indie, RPG]"

In [27]:
tags = data["tags"]

df["tags"] = df["tag_ids"].apply(
    lambda ids: [tags[i] for i in ids]
)

In [28]:
df.head()

,name,release_year,review_score,review_count,price,rating_id,genre_ids,tag_ids,developer,genres,tags
0,Counter-Strike 2,2012,87,8815087,0.00,1,"[1, 8]","[28, 18, 22, 2]",Valve,"[Action, Free To Play]","[FPS, Shooter, Multiplayer, Action]"
1,PUBG: BATTLEGROUNDS,2017,59,2557944,0.00,4,"[1, 3, 11, 8]","[46, 18, 22, 28]",PUBG Corporation,"[Action, Adventure, Massively Multiplayer, Fre...","[Survival, Shooter, Multiplayer, FPS]"
2,Dota 2,2013,82,2498969,0.00,1,"[1, 5, 8]","[24, 22, 4]",Valve,"[Action, Strategy, Free To Play]","[Free to Play, Multiplayer, Strategy]"
3,Grand Theft Auto V Legacy,2015,87,1990556,0.00,1,"[1, 3]","[2, 22]",Rockstar North,"[Action, Adventure]","[Action, Multiplayer]"
4,Terraria,2011,97,1409473,4.99,0,"[1, 3, 0, 6]","[45, 46, 8, 22]",Re-Logic,"[Action, Adventure, Indie, RPG]","[Sandbox, Survival, 2D, Multiplayer]"

In [29]:
df["primary_genre"] = df["genres"].apply(
    lambda x: x[0] if len(x) > 0 else "Unknown"
)

In [30]:
df[["name", "primary_genre"]].head()

                        name primary_genre
0           Counter-Strike 2        Action
1        PUBG: BATTLEGROUNDS        Action
2                     Dota 2        Action
3  Grand Theft Auto V Legacy        Action
4                   Terraria        Action

In [31]:
df.isnull().sum()

name             0
release_year     0
review_score     0
review_count     0
price            0
rating_id        0
genre_ids        0
tag_ids          0
developer        0
genres           0
tags             0
primary_genre    0
dtype: int64

In [32]:
df.describe()

       release_year  review_score  review_count         price     rating_id
count  82928.000000  82928.000000  8.292800e+04  82928.000000  82928.000000
mean    2020.478319     75.829985  1.782995e+03      5.158642      2.533728
std        3.302634     23.877829  3.964447e+04     11.701896      1.383689
min     2005.000000      0.000000  1.000000e+00      0.000000      0.000000
25%     2018.000000     65.000000  6.000000e+00      0.990000      2.000000
50%     2021.000000     82.000000  2.400000e+01      2.990000      2.000000
75%     2023.000000     94.000000  1.240000e+02      5.990000      4.000000
max     2025.000000    100.000000  8.815087e+06    999.980000      8.000000

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82928 entries, 0 to 82927
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           82928 non-null  str
 1   release_year   82928 non-null  int64
 2   review_score   82928 non-null  int64
 3   review_count   82928 non-null  int64
 4   price          82928 non-null  float64
 5   rating_id      82928 non-null  int64
 6   genre_ids      82928 non-null  object
 7   tag_ids        82928 non-null  object
 8   developer      82928 non-null  str
 9   genres         82928 non-null  object
 10  tags           82928 non-null  object
 11  primary_genre  82928 non-null  str
dtypes: float64(1), int64(4), object(4), str(3)
memory usage: 10.7+ MB

In [35]:
print(df.shape)

print(df["primary_genre"].value_counts().head(10))

print(df["release_year"].describe())

print(df["price"].describe())

print(df["review_score"].describe())

print(df["developer"].nunique())

(82928, 12)
primary_genre
Action          35127
Adventure       17484
Casual          15006
Indie            7982
Simulation       1791
RPG              1326
Strategy         1225
Free To Play      509
Racing            440
Violent           340
Name: count, dtype: int64
count    82928.000000
mean      2020.478319
std          3.302634
min       2005.000000
25%       2018.000000
50%       2021.000000
75%       2023.000000
max       2025.000000
Name: release_year, dtype: float64
count    82928.000000
mean         5.158642
std         11.701896
min          0.000000
25%          0.990000
50%          2.990000
75%          5.990000
max        999.980000
Name: price, dtype: float64
count    82928.000000
mean        75.829985
std         23.877829
min          0.000000
25%         65.000000
50%         82.000000
75%         94.000000
max        100.000000
Name: review_score, dtype: float64
52472

In [36]:
df.to_pickle("steam_cleaned.pkl")

# Save as CSV
df.to_csv("steam_cleaned.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [37]:
df.columns

Index(['name', 'release_year', 'review_score', 'review_count', 'price',
       'rating_id', 'genre_ids', 'tag_ids', 'developer', 'genres', 'tags',
       'primary_genre'],
      dtype='str')

In [38]:
df.head()

,name,release_year,review_score,review_count,price,rating_id,genre_ids,tag_ids,developer,genres,tags,primary_genre
0,Counter-Strike 2,2012,87,8815087,0.00,1,"[1, 8]","[28, 18, 22, 2]",Valve,"[Action, Free To Play]","[FPS, Shooter, Multiplayer, Action]",Action
1,PUBG: BATTLEGROUNDS,2017,59,2557944,0.00,4,"[1, 3, 11, 8]","[46, 18, 22, 28]",PUBG Corporation,"[Action, Adventure, Massively Multiplayer, Fre...","[Survival, Shooter, Multiplayer, FPS]",Action
2,Dota 2,2013,82,2498969,0.00,1,"[1, 5, 8]","[24, 22, 4]",Valve,"[Action, Strategy, Free To Play]","[Free to Play, Multiplayer, Strategy]",Action
3,Grand Theft Auto V Legacy,2015,87,1990556,0.00,1,"[1, 3]","[2, 22]",Rockstar North,"[Action, Adventure]","[Action, Multiplayer]",Action
4,Terraria,2011,97,1409473,4.99,0,"[1, 3, 0, 6]","[45, 46, 8, 22]",Re-Logic,"[Action, Adventure, Indie, RPG]","[Sandbox, Survival, 2D, Multiplayer]",Action